"""table update

Revision ID: 6bc9ea384b1b
Revises: 864b86975a8f
Create Date: 2025-08-22 11:41:22.757908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bc9ea384b1b'
down_revision = '864b86975a8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('mpesa_receipt', sa.String(length=120), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('checkout_response', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_payments_client_id_clients')),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], name=op.f('fk_payments_subscription_id_subscriptions')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mpesa_receipt')
    )
    op.drop_table('payment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('client_id', sa.INTEGER(), nullable=False),
    sa.Column('subscription_id', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('mpesa_receipt', sa.VARCHAR(length=120), nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=20), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('method', sa.VARCHAR(length=20), nullable=False),
    sa.Column('checkout_response', sa.VARCHAR(length=100), server_default=sa.text("('')"), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_payment_client_id_clients')),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], name=op.f('fk_payment_subscription_id_subscriptions')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mpesa_receipt')
    )
    op.drop_table('payments')
    # ### end Alembic commands ###
