"""Added client_balance to Client

Revision ID: 826aa80795aa
Revises: 6bc9ea384b1b
Create Date: 2025-09-25 11:00:09.668983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '826aa80795aa'
down_revision = '6bc9ea384b1b'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_balance', sa.Float(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('account_balance')

    # ### end Alembic commands ###
