"""made subscription_id nullable

Revision ID: 85f39325fe4a
Revises: 826aa80795aa
Create Date: 2025-09-25 11:17:51.152747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85f39325fe4a'
down_revision = '826aa80795aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('subscription_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('subscription_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
