"""Added checkout id to payment table

Revision ID: 864b86975a8f
Revises: b18bc476271f
Create Date: 2025-08-19 16:58:45.053930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '864b86975a8f'
down_revision = 'b18bc476271f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checkout_response', sa.String(length=100), nullable=False, server_default=""))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('checkout_response')

    # ### end Alembic commands ###
